name: Deploy dev

on:
  push:
    branches:
      - "dev"

jobs:
  deploy:
    uses: ./.github/workflows/deploy_reusable.yml
    name: Deploy dev
    with:
      environment: dev
    secrets: inherit
