name: Deploy production

on:
  push:
    branches:
      - "prod"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      - name: Slot swap
        run: |
          az webapp deployment slot swap \
            --ids ${{ secrets.WEBAPP_ID }} \
            --slot staging \
            --action swap
